### ISSUE TITLE
Skip Replays dropdown will crash the game

### ISSUE THREAD

**Issue by wizcreations7** [somerandomguythatneedshelp/AllInOne#1]
## Brief Description
Attempting to open the **Skip Replays** section of the plugin results in the game crashing. This issue has been tested on two separate computers.

## Steps to Reproduce
**Reproducibility**: 100%
1. Open the **BakkesMod** menu.
2. Navigate to **Plugins**.
3. Select **All In One** in the plugin list.
4. Click on the dropdown for **Skip Replays**.

## Expected Behavior
The dropdown menu should open and allow the editing of options within it.

## Actual Behavior
The dropdown menu doesn't open, and Rocket League crashes upon clicking.

**Comment by squidnugget07** [comment]
Hey Wiz, Thanks for letting me know about this bug, I will try and fix this issue

**Comment by squidnugget07** [comment]
Hey Wiz, I've updated the plugin to fix the issue you are having, please let me know if there is another issue by opening another issue on this github repo. (changes are not instant)

**Comment by wizcreations7** [comment]
> Hey Wiz, I've updated the plugin to fix the issue you are having, please let me know if there is another issue by opening another issue on this github repo. (changes are not instant)

Awesome, thank you for the hotfix, I'll be sure to open a new issue if there are any new problems.
