### ISSUE TITLE
Tournament reminder

### ISSUE THREAD

**Issue by SPoretti** [somerandomguythatneedshelp/AllInOne#2]
Hello, i know nothing about rocket league plugins and this is not an issue with yours, I was wondering if it was possible to add a notifier/schedue of some sorts somewhere in the end screen of the game to show the next tournaments so that you don't miss them by spamming next game since this happens to me a lot.

I don't expect you to do anything if its too long or if you don't want obviusly if you have any tips I might try to do it myself.

Thanks for reading

**Comment by squidnugget07** [comment]
i mean i can do that just i wont be able to start it because im out the country, when the game ends i can make a overlay visible for 5 seconds with the next tournament time, how long until the tournament and what gamemode, lmk if you want me to add anything else

**Comment by SPoretti** [comment]
Thank you very much no i don't have other ideas for now, what you described sounds how I imagined it.
No rush

**Comment by squidnugget07** [comment]
Hey SPoretti, i have added the Tournament Finder code, please note it will take a couple of days before the plugin on bakkesplugins is updated, to check this, go onto the All In One Plugin on bakkesplugins, and on the right hand side of the image, there you can see first uploaded and last updated. If, besides Last Updated, it says 7/19/2024 or 19/7/2024 (depending on your country) that means it hasent been updated. Please check for when the date is other than 7/19/2024 or 19/7/2024, Thanks

**Comment by SPoretti** [comment]
Hello i got back and tryed it out, it's pretty much perfect, i guess i see the gamemode text a bit cut but you can tell what it is, also i have to select the timezone every time i open the game but it's fine, thank you very much.

**Comment by squidnugget07** [comment]
Yea about that i'm planning a fix for this in the near future, feel free to open any other issues if you have any
