### ISSUE TITLE
RL Settings Import/ Export Tool

### ISSUE THREAD

**Issue by Compact023** [somerandomguythatneedshelp/AllInOne#3]
Hey man, 

at first read you seem like a pretty enthusiastic coder. Therefore I maybe think you would be one to create such a plugin.
I've always been annoyed about when switching accounts in RL you don't just use the Video, Control, Camera, .. Settings which are stored locally on your system. Even if you turn off sync.

Do you think it would be possible to create a plugin which can import and export those settings?
I've been looking for a way to manipulate those settings in some config file or sum such a lot of times already, with no luck.

Yeah i know that's smurfing, but who doesn't have friends they want to play with but not drop to plat with them ^^

What do you think about the idea?

Cheers,
Compact

**Comment by squidnugget07** [comment]
Hey Compact, I see you want me to expand the AIO plugin by added camera presents in which you can import and export camera settings, I can do that for you however it might take around 2-3 weeks for me to code as school is starting up and all of that but i will try and code this up, No problem, if you have anything else to say, Dont hesitate to add another comment.

**Comment by Compact023** [comment]
No pressure at all. You got all the time, even if it takes a year i dont mind.
What i was thinking was all important gameplay settings. But if you start with the game settings, i may be able to try to expand on that. Would be a nice template to start getting into C++ anyway.

**Comment by squidnugget07** [comment]
I'll try and start off with the camera settings and that, then i could try and do other plugins like keybinds, One more thing before i get into coding and figuring all this out, Bakkesmod takes a LOT of time reviewing your plugin, when i finish with this plugin Bakkesmod will take around 1-2 weeks depending how big the change was, i will send you a followup message on here to let you know once that is done

**Comment by squidnugget07** [comment]
Hey Compact, Slight delays with the update, ill start working on it in about 2-4 weeks roughly

**Comment by Compact023** [comment]
Thanks for the update!
No worries at all, tyt.
Cheers,
Compact!
Sent from Proton Mail Android
-------- Original Message --------On 03/10/2024 22:36, somerandomguythatneedshelp  wrote:
Hey Compact, Slight delays with the update, ill start working on it in about 2-4 weeks roughly

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/somerandomguythatneedshelp/AllInOne/issues/3#issuecomment-2392287339",
"url": "https://github.com/somerandomguythatneedshelp/AllInOne/issues/3#issuecomment-2392287339",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by squidnugget07** [comment]
You know, i have had a look at your github repo and it seems like you are just forking popular repos (and mine) and i don't have a problem with that, you also said that it would be a good template for C++. Basically what i'm trying to say is that you should try and learn how to contribute and make pull requests on github, so if a person (me in this case) cant do their work for whatever, you can make some changes, and they will review it and that. If you want you can learn this "codebase" and make contributions. Feel free to do so, Its totally okay if you don't want to do it i'm just saying.

**Comment by Compact023** [comment]
Hey man, thats a great suggestion, I'm willing to do that. But time consttaints are getring bigger for me, year by year, due to work.
I saw your offer on bakkesmod and thught why not ask. I really like the way you get expirience in. I myswlf when learning to code have to have a project where i see some sort of sense in. I think you achieve that, with youe principle
Cheers,
Compact!
Sent from Proton Mail Android
-------- Original Message --------On 04/10/2024 21:41, somerandomguythatneedshelp  wrote:
You know, i have had a look at your github repo and it seems like you are just forking popular repos (and mine) and i don't have a problem with that, you also said that it would be a good template for C++. Basically what i'm trying to say is that you should try and learn how to contribute and make pull requests on github, so if a person (me in this case) cant do their work for whatever, you can make some changes, and they will review it and that. If you want you can learn this "codebase" and make contributions. Feel free to do so, Its totally okay if you don't want to do it i'm just saying.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/somerandomguythatneedshelp/AllInOne/issues/3#issuecomment-2394456800",
"url": "https://github.com/somerandomguythatneedshelp/AllInOne/issues/3#issuecomment-2394456800",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by squidnugget07** [comment]
No problem, im currently working on a python project until i get my main pc back, feel free to make a PR, lmk if you have any questions

**Comment by squidnugget07** [comment]
Hey Compact, AIO is almost ready, i have finished Presets, I am just working on fixing some bugs, please excuse some of the code comments if you wish to see the finished code, i will send a follow up message when the plugin is complete and i will close this issue

**Comment by squidnugget07** [comment]
Hey Compact, Plugin is under review and will be available when bakkesmod moderators approve it, i will now close this issue

**Comment by Compact023** [comment]
Hey man, 
Thanks for the frequent status updates!
I'll give it a try... if that now does what I think, you'll need to show me some sort of a tip char... would love to buy ya a coddle or 2
Cheers,
Compact!
Sent from Proton Mail Android
-------- Original Message --------On 02/11/2024 01:54, somerandomguythatneedshelp  wrote:
Hey Compact, Plugin is under review and will be available when bakkesmod moderators approve it, i will now close this issue

**Comment by squidnugget07** [comment]
Please note that the plugin wont immediately update and may take up to 4 months max
